name: advanced_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  awesome_flutter_extensions: 1.3.0
  cupertino_icons: 1.0.8
  dartx: 1.2.0
  flutter_cache_manager: 3.4.1
  http: 1.3.0
  rxdart: 0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  file: 7.0.1
  flutter_lints: 5.0.0
  network_image_mock: 2.1.1

flutter:
  uses-material-design: true
