name: advanced_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  awesome_flutter_extensions: 1.2.0
  cupertino_icons: ^1.0.2
  dartx: 1.2.0
  flutter_cache_manager: 3.3.2
  http: 1.2.1
  rxdart: 0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  file: 7.0.0
  flutter_lints: ^3.0.0
  network_image_mock: 2.1.1

flutter:
  uses-material-design: true
